[workspace]
members = [
  # "packages/rxrs",
  "abra/abra",
  "abra/core/*",
  "abra/ai/core",
  "abra/ai/super-resolution",
  "abra/plugins/*",
  "apps/examples/*",
  "apps/examples/ai/super-resolution",
  "packages/node/alakazam",
]
exclude = ["apps/examples/ai"]
default-members = [
  # "packages/rxrs",
  # "packages/abra",
  # "packages/alakazam",
  "apps/examples/*",
]

resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
rayon = { version = "1.12.0" }
rand = { version = "0.10.3" }
tensorflow = { version = "0.21.0" }
burn = { version = "0.21.0" }
ndarray = { version = "0.17.2", features = ["rayon"] }
wgpu = { version = "30.0.1" }
pollster = { version = "1.0.1" }
bytemuck = { version = "1.25.2" }
futures = { version = "0.3.34" }
anyhow = { version = "1.0.104" }
saphyr = { version = "0.1.0" }
ctor = { version = "1.0.13" }
paste = { version = "1.0.15" }
ort = { version = "2.0.0-rc.13" }
napi = { version = "3.12.7", default-features = false, features = ["napi4"] }
napi-derive = { version = "3.6.8" }
swash = { version = "0.2.10" }

# Packages
abra = { path = "./abra/abra" }
adjustments = { path = "./abra/core/adjustments" }
canvas = { path = "./abra/core/canvas" }
abra-core = { path = "./abra/core/core" }
drawing = { path = "./abra/core/drawing" }
filters = { path = "./abra/core/filters" }
mask = { path = "./abra/core/mask" }
options = { path = "./abra/core/options" }
primitives = { path = "./abra/core/primitives" }
tools = { path = "./abra/core/tools" }

gpu = { path = "./abra/core/gpu" }
gpu_integration = { path = "./abra/core/gpu_integration" }
typography = { path = "./abra/core/typography" }

# Abra Plugins
collage = { path = "./abra/plugins/collage" }

# Abra AI Packages
abra-ai-core = { path = "./abra/ai/core" }
abra-super-resolution = { path = "./abra/ai/super-resolution" }

# Node Packages
alakazam = { path = "./packages/node/alakazam" }

[workspace.dependencies.uuid]
version = "1.24.0"
features = ["v4"]
