export enum ButtonType {
    Primary,
    Secondary,
}

export component ActionButton inherits Rectangle {
    in property <string> text <=> text.text;
    in property <ButtonType> type: ButtonType.Primary;

    callback clicked();

    height: 40px;
    border-radius: 20px;
    min-width: 100px;

    background: type == ButtonType.Primary ? #0078d4 : transparent;
    border-color: type == ButtonType.Primary ? transparent : #ffffff;
    border-width: 2px;

    text := Text {
        font-size: 14px;
        font-weight: type == ButtonType.Primary ? 700 : 400;
        letter-spacing: 1px;
        vertical-alignment: center;
        horizontal-alignment: center;
    }

    TouchArea {
        mouse-cursor: pointer;
        clicked => {
            root.clicked();
        }
    }
}
