[package]
name = "canvas"
version = "1.0.0"
edition = "2024"

[dependencies]
abra-core = { workspace = true }
filters = { workspace = true }
drawing = { workspace = true }
typography = { workspace = true }

rayon = { workspace = true }
uuid = { workspace = true }

[lib]
crate-type = ["rlib"]

[dev-dependencies]
gpu = { path = "../gpu" }
adjustments = { workspace = true }
