import { EffectSpec as Effect } from "@alakazam/mobile";
import { EditSection } from "../edit-sections";

export const adjustments: EditSection = {
  key: 'section-adjustments',
  label: 'Adjustments',
  controls: [
    {
      kind: 'slider',
      key: 'action-brightness',
      label: 'Brightness',
      min: -100,
      max: 100,
      defaultValue: 0,
      applyOnSelect: false,
      apply: (image, value) => image.applyEffect(Effect.Brightness.new({ amount: Math.round(value) })),
      live: value => Effect.Brightness.new({ amount: Math.round(value) }),
    },
    {
      kind: 'slider',
      key: 'action-contrast',
      label: 'Contrast',
      min: -100,
      max: 100,
      defaultValue: 0,
      applyOnSelect: false,
      apply: (image, value) => image.applyEffect(Effect.Contrast.new({ amount: Math.round(value) })),
      live: value => Effect.Contrast.new({ amount: Math.round(value) }),
    },
    {
      kind: 'slider',
      key: 'action-saturation',
      label: 'Saturation',
      min: -100,
      max: 100,
      defaultValue: 0,
      applyOnSelect: false,
      apply: (image, value) => image.applyEffect(Effect.Saturation.new({ amount: Math.round(value) })),
      live: value => Effect.Saturation.new({ amount: Math.round(value) }),
    },
    {
      kind: 'slider',
      key: 'action-exposure',
      label: 'Exposure',
      min: -5,
      max: 5,
      step: 0.1,
      defaultValue: 0,
      applyOnSelect: false,
      apply: (image, value) => image.applyEffect(Effect.Exposure.new({ exposure: value, offset: 0.0, gammaCorrection: 1.0 })),
      live: value => Effect.Exposure.new({ exposure: value, offset: 0.0, gammaCorrection: 1.0 }),
    },
    {
      kind: 'slider',
      key: 'action-vibrance',
      label: 'Vibrance',
      min: -100,
      max: 100,
      defaultValue: 0,
      applyOnSelect: false,
      apply: (image, value) => image.applyEffect(Effect.Vibrance.new({ vibrance: Math.round(value), saturation: 0 })),
      live: value => Effect.Vibrance.new({ vibrance: Math.round(value), saturation: 0 }),
    },
  ],
}