/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Image {
  width: number
  height: number
  constructor(data: Buffer, width: number, height: number)
}

export declare class Layer {
  /**
   * Gets the name of the layer.
   * @returns The name of the layer.
   */
  get name(): string
  /**
   * Gets the opacity of the layer.
   * @returns The opacity of the layer.
   */
  get opacity(): number
  /**
   * Gets the visibility of the layer.
   * @returns The visibility of the layer.
   */
  get visible(): boolean
  /**
   * Sets the name of the layer.
   * @param name The new name of the layer.
   */
  setName(name: string): this
  /**
   * Sets the blend mode of the layer.
   * @param blendMode The new blend mode of the layer.
   */
  setBlendMode(blendMode: 'normal' | 'darken' | 'average' | 'multiply' | 'color-burn' | 'linear-burn' | 'lighten' | 'screen' | 'color-dodge' | 'linear-dodge' | 'overlay' | 'soft-light' | 'hard-light' | 'vivid-light' | 'linear-light' | 'pin-light' | 'hard-mix' | 'difference' | 'exclusion' | 'subtract' | 'divide' | 'hue' | 'saturation' | 'color' | 'luminosity' | 'reflect' | 'glow' | 'phoenix' | 'negation' | 'grain-extract' | 'grain-merge'): this
  /**
   * Sets the opacity of the layer.
   * @param opacity The new opacity of the layer.
   */
  setOpacity(opacity: number): this
  /**
   * Sets the visibility of the layer.
   * @param visible The new visibility of the layer.
   */
  setVisibility(visible: boolean): this
  /** Mark the parent canvas as needing recompose (forces a recompose on save). */
  markDirty(): this
  /**
   * Gets the underlying image of the layer.
   * @param size Optional size to scale the image to. If only width or height is provided, the other dimension will be scaled proportionally.
   * @returns The image of the layer.
   */
  imageData(size?: [number, number] | undefined | null): ImageData
  /**
   * Sets a new image for the layer.
   * @param data The image data as a Buffer.
   * @param width The width of the image.
   * @param height The height of the image.
   */
  setImageData(data: ImageData): this
  /**
   * Sets the position of the layer.
   * @param position The new position of the layer.
   */
  setPosition(position: Position): this
  /**
   * Sets the anchor point of the layer.
   * @param anchor The new anchor point of the layer. Can be one of: '
   */
  setAnchor(anchor: 'top-left' | 'top-center' | 'top-right' | 'center-left' | 'center' | 'center-right' | 'bottom-left' | 'bottom-center' | 'bottom-right' | null): this
  setRotation(angle: number): this
  /**
   * Gets the metadata of the layer.
   * @returns The layer metadata.
   */
  metadata(): LayerMetadata
}

/**
 * Represents a project. A project has one root canvas.
 * The canvas then contains other layers and canvases.
 */
export declare class Project {
  /**
   * Create a new blank project with the given name and dimensions.
   * @param name The name of the project.
   * @param width The width of the canvas.
   * @param height The height of the canvas.
   * @returns A new Project instance.
   */
  constructor(name: string, width: number, height: number)
  /**
   * Create a new project by loading an image from a file path.
   * @param name The name of the project.
   * @param filePath The file path to load the image from.
   * @returns A new Project instance.
   */
  constructor(name: string, filePath: string)
  /**
   * Gets the project's active layers.
   * @returns The active layers, or an empty array if none are set.
   */
  activeLayers(): Array<LayerMetadata>
  /**
   * Sets multiple active layers by their IDs.
   * @param layerIds An array of layer IDs to set as active.
   */
  setActiveLayers(layerIds: Array<string>): this
  /**
   * Sets a single active layer by its ID.
   * @param layerId The ID of the layer to set as active.
   */
  setActiveLayer(layerId: string): this
  /**
   * Composites the project's canvas and returns the resulting image data.
   * @returns The composited image data.
   */
  composite(): ImageData
  /**
   * Gets the name of the project.
   * @returns The name of the project.
   */
  get name(): string
  /**
   * Gets the unique ID of the project.
   * @returns The unique ID of the project.
   */
  get id(): string
  /**
   * Gets the width of the canvas.
   * @returns The width of the canvas.
   */
  get width(): number
  /**
   * Gets the height of the canvas.
   * @returns The height of the canvas.
   */
  get height(): number
  /**
   * Gets the layers of the canvas.
   * @returns An array of layers in the canvas.
   */
  get layerMetadata(): Array<LayerMetadata>
  /**
   * Adds a new layer to the canvas from a file path.
   * @param name The name of the layer.
   * @param filePath The file path to load the image from.
   */
  addLayerFromPath(name: string, filePath: string): LayerMetadata
  /**
   * Adds a new empty layer to the canvas.
   * @param name The name of the layer.
   */
  addEmptyLayer(name: string): LayerMetadata
  /**
   * Adds a new adjustment layer to the canvas.
   * @param name The name of the layer.
   * @param adjustmentType The type of adjustment layer to add (e.g., "brightness-contrast").
   */
  addAdjustmentLayer(name: string, adjustmentType: string): LayerMetadata
  /**
   * Gets a layer by its index.
   * @param index The index of the layer.
   * @returns The layer at the given index, or null if not found.
   */
  getLayerByIndex(index: number): Layer | null
  /**
   * Gets a layer by its UUID.
   * @param id The UUID of the layer.
   * @returns The layer with the given UUID, or null if not found.
   */
  getLayerById(id: string): Layer | null
  /**
   * Gets a layer by its name.
   * @param name The name of the layer.
   * @returns The layer with the given name, or null if not found.
   */
  getLayerByName(name: string): Layer | null
  /**
   * Moves a layer to a new index in the layer stack.
   * @param layer The layer to move.
   * @param newIndex The new index to move the layer to.
   */
  moveLayerTo(layer: Layer, newIndex: number): this
  /**
   * Moves a layer up one position in the layer stack.
   * @param layer The layer to move.
   */
  moveLayerUp(layer: Layer): this
  /**
   * Moves a layer down one position in the layer stack.
   * @param layer The layer to move.
   */
  moveLayerDown(layer: Layer): this
  /**
   * Moves a layer to the top of the layer stack.
   * @param layer The layer to move.
   */
  moveLayerToTop(layer: Layer): this
  /**
   * Reorders the layers in the layer stack according to the given array of layer IDs.
   * @param newOrderIds An array of layer IDs representing the new order.
   */
  reorderLayers(newOrderIds: Array<string>): this
  /**
   * Delate a layer from the layer stack.
   * @param layer The layer to delete.
   */
  deleteLayer(layer: Layer): this
  /**
   * Moves a layer to the bottom of the layer stack.
   * @param layer The layer to move.
   */
  moveLayerToBottom(layer: Layer): this
  /**
   * Get the image data of a specific layer.as it would appear when composited without the other layers.
   * @param layer The layer to composite.
   * @param maxSize Optional maximum size (in pixels) for the longest dimension of the resulting image. If the composited image exceeds this size, it will be scaled down proportionally.
   * @returns The image data of the composited layer.
   */
  compositeLayer(layer: Layer, maxSize?: number | undefined | null): ImageData
  /**
   * Gets the metadata of the project.
   * @returns The project metadata.
   */
  metadata(): ProjectMetadata
  save(filePath: string): void
}

/** Result of opening an image, includes dimensions for canvas rendering. */
export interface AbraImageData {
  data: Buffer
  width: number
  height: number
}

export declare function autoColor(layer: Layer): void

export declare function autoTone(layer: Layer): void

/**
 * Blurs the image using a box blur algorithm.
 * @param layer The layer to apply the box blur to.
 * @param radius The radius of the box blur.
 */
export declare function boxBlur(layer: Layer, radius: number): void

export declare function brightness(layer: Layer, value: number): void

export declare function contrast(layer: Layer, value: number): void

export declare function despeckle(layer: Layer, radius: number, threshold: number): void

export declare function exposure(layer: Layer, exposure: number, offset: number, gamma: number): void

/**
 * Applies a Gaussian blur to the image.
 * @param layer The layer to apply the Gaussian blur to.
 * @param radius The radius of the Gaussian blur.
 */
export declare function gaussianBlur(layer: Layer, radius: number): void

export declare function grayscale(layer: Layer): void

export declare function invert(layer: Layer): void

/** Options for iris (aperture) in lens blur. */
export interface IrisOptions {
  /** Shape of the aperture */
  shape: 'triangle' | 'square' | 'pentagon' | 'hexagon' | 'heptagon' | 'octagon'
  /** Radius of the aperture */
  radius: number
  /** Curvature of the blades (0.0 = straight, 1.0 = fully curved) */
  bladeCurvature: number
  /** Rotation of the aperture in degrees */
  rotation: number
}

export interface LayerMetadata {
  /** A UUID string identifying the layer. */
  id: string
  /** The name of the layer. */
  name: string
  /** The id of the project this layer belongs to. */
  projectId: string
  /** The blend mode for the layer. */
  blendMode: string
  /** The opacity of the layer (0.0 to 1.0). */
  opacity: number
  /** Whether the layer is visible. */
  visible: boolean
  /** The order of the layer in the layer stack (0 is bottom). */
  order: number
  /** The adjustment type if this is an adjustment layer. */
  adjustmentType?: string
  /** The width of the layer in pixels. */
  width: number
  /** The height of the layer in pixels. */
  height: number
  /** The x offset of the layer in pixels. */
  x: number
  /** The y offset of the layer in pixels. */
  y: number
  /** The rotation angle of the layer in degrees. */
  angle: number
}

/**
 * Applies a lens blur to the image with specified options.
 * @param layer The layer to apply the lens blur to.
 * @param options Configuration options for the lens blur.
 */
export declare function lensBlur(layer: Layer, options?: LensBlurOptions | undefined | null): void

/** Options for lens blur filter. */
export interface LensBlurOptions {
  /** Iris (aperture) configuration. */
  iris: IrisOptions
  /** Specular highlight boost; None to disable. */
  specular?: SpecularOptions
  /** Output noise/dither; None to disable. */
  noise?: NoiseOptions
  /** Number of samples per pixel. Higher is smoother but slower. */
  samples: number
}

export declare function median(layer: Layer, radius: number): void

/**
 * Applies a motion blur to the image.
 * @param layer The layer to apply the motion blur to.
 * @param angle The angle of the motion blur in degrees.
 * @param distance The distance of the motion blur in pixels.
 */
export declare function motionBlur(layer: Layer, angle: number, distance: number): void

/**
 * Applies a noise filter to the image.
 * @param layer The layer to apply the noise filter to.
 * @param amount The amount of noise to add.
 * @param distribution The distribution type of the noise ("uniform" or "gaussian").
 */
export declare function noise(layer: Layer, amount: number, distribution: string): void

/** Options for noise added after lens blur. */
export interface NoiseOptions {
  /** Amount of noise to add. */
  amount: number
  /** Distribution type: "uniform" or "gaussian". */
  distribution: 'uniform' | 'gaussian'
}

/**
 * Applies a pinch distortion effect to the image.
 * @param layer The layer to apply the pinch effect to.
 * @param amount The amount of pinch effect to apply. Positive values pinch inward, negative values bulge outward.
 */
export declare function pinch(layer: Layer, amount: number): void

/** Position object for setting a layer position. */
export interface Position {
  /** The x coordinate of the layer. */
  x?: number
  /** The y coordinate of the layer. */
  y?: number
}

export interface ProjectMetadata {
  /** A UUID string identifying the project. */
  id: string
  /** The name of the project. */
  name: string
  /** The width of the project in pixels. */
  width: number
  /** The height of the project in pixels. */
  height: number
  /** The layers that are currently active/selected. */
  activeLayers: Array<LayerMetadata>
  /** All layers in the project. */
  layers: Array<LayerMetadata>
}

/**
 * Applies a ripple distortion effect to the image.
 * @param layer The layer to apply the ripple effect to.
 * @param amount The amount of ripple effect to apply. Positive values create inward ripples, negative values create outward ripples.
 * @param size The size of the ripple effect. Can be "small", "medium", or "large".
 * @param shape The shape of the ripple effect. Can be "circular", "square", "random", or an angle (0-360 degrees, where 0 = vertical, 90 = horizontal).
 */
export declare function ripple(layer: Layer, amount: number, size: "small" | "medium" | "large", shape: "circular" | "square" | "random" | number): void

/** Options for specular highlights in lens blur. */
export interface SpecularOptions {
  /** Brightness multiplier for specular highlights. */
  brightness: number
  /** Threshold for specular highlights (0.0 - 1.0). */
  threshold: number
}

/**
 * Applies a surface blur to the image.
 * @param layer The layer to apply the surface blur to.
 * @param radius The radius of the surface blur.
 * @param threshold The threshold for the surface blur.
 */
export declare function surfaceBlur(layer: Layer, radius: number, threshold: number): void

export declare function vibrance(layer: Layer, vibrance: number, saturation: number): void
