# Generated by uniffi-bindgen-react-native
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "AlakazamMobile"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => min_ios_version_supported }
  s.source       = { :git => "https://github.com/TheColorRed/rust-image.git", :tag => "#{s.version}" }

  # The Rust library as a dynamic framework: CocoaPods embeds it in the app
  # and signs it with the app's identity. Nothing here is compiled.
  s.vendored_frameworks = "ios/alakazam_mobile.xcframework"
  # The player compiles the only native code. A missing pod here is the
  # earliest sign that @ubjs/react-native is not a direct dependency of the app.
  s.dependency "UbjsReactNative"
end
